version: "3.2"
services:
    app:
        container_name: products-api
        build: .
        ports:
          - "5006:8085"
        depends_on: 
          - mysqldb
    mysqldb:
        container_name: products-db
        build: mssql/.
        ports:
          - "1433:1433"
        environment:    
          MSSQL_PID: "Developer"
          MSSQL_USER: "sa"
          MSSQL_SA_PASSWORD: "Passw0rd"
          ACCEPT_EULA: "Y"              